version: '3'
services:
  db:
    image: postgres:alpine3.19
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    env_file:
      - ./.env

volumes:
  db-data:
    driver: local

networks:
  app:
    driver: bridge